### ISSUE TITLE
第四章倒数第二节,添加go语言实例

### ISSUE THREAD

**Issue by yihaibin1** [xiaopeng163/docker.tips#6]
dockerfile:
FROM golang:alpine3.15 AS builder
COPY app.go /src/app.go
WORKDIR /src

RUN go build app.go

FROM alpine:3.17.0
COPY --from=builder /src/app /src/app 

EXPOSE 8080

CMD ./src/app

golang:
package main

import (
	"fmt"
	"net/http"
)

func test(w http.ResponseWriter,r  *http.Request){
	w.Write([]byte("Hello golang"))
}

func main() {
	http.HandleFunc("/",test)
	err:=http.ListenAndServe(":8080",nil)
	if err!=nil{
		fmt.Println(err)
	}
}

**Comment by xiaopeng163** [comment]
can you create a pull request? thanks

**Comment by Lan-ce-lot** [comment]
I have submitted a PR 👀
